# Starter pipeline
- task: DotNetCoreCLI@2
  inputs:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    command: 'build'
    projects: 'https://github.com/afrozquadri/ntmswebdb.git'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    appType: 'webApp'
    WebAppName: 
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
